name: ETL
on:
  schedule:
    - cron: "59 5 * * *"
  workflow_dispatch:
jobs:
  etl:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1061748385198/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "jamulus-archive@dtinth-storage-space.iam.gserviceaccount.com"
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.12
      - run: bun install
      - run: bun src/loadAll.ts
      - name: "Generate stats"
        run: bun src/generateStats.ts
      - name: "Commit changes"
        run: |
          git config user.name 'dtinth-bot'
          git config user.email 'dtinth-bot@users.noreply.github.com'
          git add STATS.md
          git diff --staged --quiet || git commit -m "Update statistics [skip ci]"
          git push