name: ETL
on:
  push:
    branches:
      - main
jobs:
  etl:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.3.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "https://iam.googleapis.com/projects/1061748385198/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "jamulus-archive@dtinth-storage-space.iam.gserviceaccount.com"
      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set project dtinth-storage-space
          gcloud services list
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.12
